In [7]:
from transformers import AutoTokenizer

prompt = "It was a dark and stormy"
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-0.5B")
input_ids = tokenizer(prompt)["input_ids"]
print(input_ids)

[2132, 572, 264, 6319, 323, 13458, 88]


In [8]:
for token in input_ids:
    print(token, "\t:", tokenizer.decode(token))

2132 	: It
572 	:  was
264 	:  a
6319 	:  dark
323 	:  and
13458 	:  storm
88 	: y


In [9]:
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B")

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/138 [00:00<?, ?B/s]

In [11]:
input_ids = tokenizer(prompt,return_tensors="pt")["input_ids"]

outputs = model(input_ids)


In [17]:
print(outputs.logits.shape)

final_logits = outputs.logits[0,-1]

torch.Size([1, 7, 151936])


In [19]:
tokenizer.decode(final_logits.argmax())

' night'

In [23]:
import torch

top10_logits = torch.topk(final_logits,10)

for index in top10_logits.indices:
    print(tokenizer.decode(index))

 night
 evening
 day
 morning
 winter
 afternoon
 Saturday
 Sunday
 Friday
 October


In [28]:
top10 = torch.topk(final_logits.softmax(dim=0),10)

for value,index in zip(top10.values,top10_logits.indices):
    print(tokenizer.decode(index),value.item())

 night 0.88706374168396
 evening 0.04300227761268616
 day 0.02191721275448799
 morning 0.004866069182753563
 winter 0.00449405238032341
 afternoon 0.0027222216594964266
 Saturday 0.002517268992960453
 Sunday 0.0018722137901932001
 Friday 0.0017145765013992786
 October 0.0016489927656948566


In [116]:
output_ids = model.generate(input_ids, max_new_tokens = 100)
decoded_text = tokenizer.decode(output_ids[0]) #Greedy decoding

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.


In [117]:
print(decoded_text)

It was a dark and stormy night. The sky was dark and the wind was howling. The rain was pouring down and the lightning was flashing. The sky was dark and the wind was howling. The rain was pouring down and the lightning was flashing. The sky was dark and the wind was howling. The rain was pouring down and the lightning was flashing. The sky was dark and the wind was howling. The rain was pouring down and the lightning was flashing. The sky was dark and the wind was howling


In [34]:
beam_output = model.generate( 
    input_ids,
    max_new_tokens = 30,
    num_beams=5
) #Beam decoding


decoded_text = tokenizer.decode(beam_output[0]) #Greedy decoding

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.


In [35]:
print(decoded_text)

It was a dark and stormy night. The wind was howling, and the rain was pouring down. The sky was dark and gloomy, and the air was filled with the


In [122]:
beam_output = model.generate( 
    input_ids,
    max_new_tokens = 1000,
    num_beams=5,
    repetition_penalty = 2.0
) #Beam decoding


decoded_text = tokenizer.decode(beam_output[0]) 

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.


In [126]:
print(decoded_text)

It was a dark and stormy night. The sky was filled with thunder and lightning, and the wind howled in the distance. It was raining cats and dogs, and the streets were covered in puddles of water.

As I walked down the street, I noticed a group of children playing in the rain. They were laughing and having fun, but I couldn't help but feel a sense of unease creeping up on me.

Suddenly, I heard a loud noise coming from behind me. I turned around to see a man with a gun pointing his weapon at me. My heart raced as I realized what was happening.

"What are you doing out here?" he asked, his voice low and menacing.

"I don't know what you're talking about," I said, trying to keep my voice steady. "I'm just walking down the street."

The man raised his gun and pointed it at me again. "You'll pay for what you've done," he said, his voice dripping with venom.

I took a deep breath and tried to remain calm. "I didn't do anything wrong," I said. "I was just walking down the street."

The man sh

In [39]:
output_sample = model.generate( 
    input_ids,
    max_new_tokens = 38,
    do_sample=True,
    top_k = 0
) 
decoded_text = tokenizer.decode(output_sample[0]) 
print(decoded_text)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.


It was a dark and stormy night, like any typical warm, rainy, night with plenty of raindrops falling.I couldn't see clearly because I was sitting really close to Tiffany and it was raining hard. Nonetheless that made


In [115]:
output_sample = model.generate( 
    input_ids,
    max_new_tokens = 100,
    do_sample=True,
    top_k = 0,
    temperature = 1
) 
decoded_text = tokenizer.decode(output_sample[0]) 
print(decoded_text)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.


It was a dark and stormy morning as Naomi Earp got ready for an early day at the California State University at Rio Costa. She had no worries that the day would be spent in class, plowing through dozens of assigned reading assignments, accomplished the work she had bought at the Cyberspace Computer Museum in Tangmere, and also spent most of the morning in a different place, a rough circle of grassland on the edge of her athletic field. entry in December 1913. After a few curious generations of


In [139]:
tokenizer.encode(" positive"),tokenizer.encode(" negative")


def score(review):
    prompt = f"""Question: Is the following review positive or negative about the movie? 
    Review: {review} Answer:"""

    input_ids = tokenizer(prompt,return_tensors="pt").input_ids
    final_logits = model(input_ids).logits[0,-1][[6785,8225]]
    if final_logits[0] > final_logits[1]:
        print("Positive")
        print(final_logits.softmax(dim=0))
    else:
        print("Negative")
        print(final_logits.softmax(dim=0))
    

In [141]:
score("This movie is the bomb!")

score("This movie bombed")

score("This movie blew me away with how good the ending was")

Positive
tensor([0.5675, 0.4325], grad_fn=<SoftmaxBackward0>)
Negative
tensor([0.2045, 0.7955], grad_fn=<SoftmaxBackward0>)
Negative
tensor([0.2962, 0.7038], grad_fn=<SoftmaxBackward0>)


In [146]:

def translate(sentence):
    prompt = f"""\
    Translate English to Spanish:

    English: I dont not speak Spanish.
    Spanish: No hablo español.

    English: {sentence}
    Spanish:
    """

    inputs = tokenizer(prompt,return_tensors="pt").input_ids
    output = model.generate(inputs,
                            max_new_tokens = 15
                            )
    
    return tokenizer.decode(output[0])


In [148]:
print(translate("I like football"))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.


    Translate English to Spanish:

    English: I dont not speak Spanish.
    Spanish: No hablo español.

    English: I like football
    Spanish:
     "Me gusta el fútbol"

    English: I like to


In [150]:
from transformers import pipeline

fill_masker = pipeline("fill-mask", model="bert-base-uncased")
fill_masker("The [MASK] is made of milk.")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

c:\Users\Pette\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Pette\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For bet

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Device set to use cuda:0


[{'score': 0.19546672701835632,
  'token': 9841,
  'token_str': 'dish',
  'sequence': 'the dish is made of milk.'},
 {'score': 0.1290750503540039,
  'token': 8808,
  'token_str': 'cheese',
  'sequence': 'the cheese is made of milk.'},
 {'score': 0.1059066578745842,
  'token': 6501,
  'token_str': 'milk',
  'sequence': 'the milk is made of milk.'},
 {'score': 0.04112076386809349,
  'token': 4392,
  'token_str': 'drink',
  'sequence': 'the drink is made of milk.'},
 {'score': 0.037123341113328934,
  'token': 7852,
  'token_str': 'bread',
  'sequence': 'the bread is made of milk.'}]

In [153]:
classifier = pipeline("text-classification", model="tabularisai/multilingual-sentiment-analysis")
classifier("This movie blew me away with how good it was")

Device set to use cuda:0


[{'label': 'Positive', 'score': 0.5673620700836182}]

In [3]:
!pip uninstall genaibook
!pip install genaibook

^C


In [6]:
import requests
from PIL import Image

from genaibook.core import SampleURL


url = SampleURL.CatExample

image = Image.open(requests.get(url,stream=True).raw)
image

ImportError: cannot import name 'SampleURL' from 'genaibook.core' (c:\Users\Pette\anaconda3\Lib\site-packages\genaibook\core.py)

In [ ]:
from transformers import pipeline
pipe = pipeline(
    "zero-shot-image-classification",
    model="openai/clip-vit-base-patch32"


)


labels = ["cat","dog","zebra","feline"]


None


In [ ]:
print(pipe(image,candidate=labels))
image